name: majootestcase
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  sqflite: ^2.0.1
  equatable: ^2.0.3
  flutter_screenutil: ^5.0.3
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.11
  path_provider: ^2.0.8
  path: ^1.8.0
  pretty_dio_logger: ^1.2.0-beta-1
  another_flushbar: ^1.10.28

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  mockito: ^5.0.17

flutter:
  uses-material-design: true

